// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbscfxnaimfbkbvheyho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhic2NmeG5haW1mYmtidmhleWhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0ODk3NjQsImV4cCI6MjA2NjA2NTc2NH0.O6f_tKMYdkvR0cwaYRY7I-WgQdxts759eTGEy0IX8Ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);